//  <auto-generated>
//		This code was generated by the Voodoo-ass ResourceLocator v2.4.0 T4 Template.
//		LIC.Services.ITOperations.AnimalCompliance.WebApi 0.2.2.0 
//		   
//		Changes to this file will be lost if the code is regenerated.
//	</auto-generated>

using System;

namespace LIC.Services.ITOperations.AnimalCompliance.WebApi 
{
	namespace v0 
	{
		public static class ResourceLocator
		{
			public const string ServiceName = "ITOperations.AnimalCompliance";
			public static class NaitMovementEvent 
			{
				public const string ResourceName = "ITOperations.AnimalCompliance.NaitMovementEvent";
				public static string Put(Guid eventId)
				{
					var location = "v0/event/naitmovement/{eventId}"
						.Replace("{eventId}", eventId.ToString())	;
					return location.ToLowerInvariant();
				}
			}

		}
	}
}

