//  <auto-generated>
//      This code was generated by the Voodoo-ass ResourceLocator v2.3 T4 Template.
//		
//		LIC.Services.ITOperations.Treatment.WebApi 0.6.0.0 
//		   
//      Changes to this file will be lost if the code is regenerated.
//  </auto-generated>

using System;

namespace LIC.Services.ITOperations.Treatment.WebApi 
{
	namespace v0 
	{
		public static class ResourceLocator
		{
			public const string ServiceName = "ITOperations.Treatment";
			public static class AddDoseEvent 
			{
				public const string ResourceName = "ITOperations.Treatment.AddDoseEvent";
				public static string Put(Guid eventId)
				{
					var location = "v0/event/treatment/adddose/{eventId}".Replace("{eventId}", eventId.ToString());
					return location.ToLowerInvariant();
				}
					public static string Get(Guid eventId)
				{
					var location = "v0/event/treatment/adddose/{eventId}".Replace("{eventId}", eventId.ToString());
					return location.ToLowerInvariant();
				}
			}
			public static class CompleteHealthPlanEvent 
			{
				public const string ResourceName = "ITOperations.Treatment.CompleteHealthPlanEvent";
				public static string Put(Guid eventId)
				{
					var location = "v0/event/treatment/completehealthplan/{eventId}".Replace("{eventId}", eventId.ToString());
					return location.ToLowerInvariant();
				}
					public static string Get(Guid eventId)
				{
					var location = "v0/event/treatment/completehealthplan/{eventId}".Replace("{eventId}", eventId.ToString());
					return location.ToLowerInvariant();
				}
			}
			public static class EnrolAnimalInHealthPlanEvent 
			{
				public const string ResourceName = "ITOperations.Treatment.EnrolAnimalInHealthPlanEvent";
				public static string Put(Guid eventId)
				{
					var location = "v0/event/treatment/enrolanimalinhealthplan/{eventId}".Replace("{eventId}", eventId.ToString());
					return location.ToLowerInvariant();
				}
					public static string Get(Guid eventId)
				{
					var location = "v0/event/treatment/enrolanimalinhealthplan/{eventId}".Replace("{eventId}", eventId.ToString());
					return location.ToLowerInvariant();
				}
			}
			public static class GiveDoseEvent 
			{
				public const string ResourceName = "ITOperations.Treatment.GiveDoseEvent";
				public static string Put(Guid eventId)
				{
					var location = "v0/event/treatment/givedose/{eventId}".Replace("{eventId}", eventId.ToString());
					return location.ToLowerInvariant();
				}
					public static string Get(Guid eventId)
				{
					var location = "v0/event/treatment/givedose/{eventId}".Replace("{eventId}", eventId.ToString());
					return location.ToLowerInvariant();
				}
			}
		}
	}
}