//  <auto-generated>
//      This code was generated by the Voodoo-ass ResourceLocator v2.3 T4 Template.
//		
//		LIC.Services.ITOperations.Mating.WebApi 0.1.0.0 
//		   
//      Changes to this file will be lost if the code is regenerated.
//  </auto-generated>

using System;

namespace LIC.Services.ITOperations.Mating.WebApi
{
    namespace v0
    {
        public static class ResourceLocator
        {
            public const string ServiceName = "ITOperations.Mating";
            public static class HeatEvent
            {
                public const string ResourceName = "ITOperations.Mating.HeatEvent";
                public static string Put(Guid eventId)
                {
                    var location = "v0/event/heat/{eventId}".Replace("{eventId}", eventId.ToString());
                    return location.ToLowerInvariant();
                }
            }
            public static class PregnancyDiagnosisEvent
            {
                public const string ResourceName = "ITOperations.Mating.PregnancyDiagnosisEvent";
                public static string Put(Guid eventId)
                {
                    var location = "v0/event/pregnancydiagnosis/{eventId}".Replace("{eventId}", eventId.ToString());
                    return location.ToLowerInvariant();
                }
            }
            public static class NaturalMatingEvent
            {
                public const string ResourceName = "ITOperations.Mating.NaturalMatingEvent";
                public static string Put(Guid eventId)
                {
                    var location = "v0/event/naturalmating/{eventId}".Replace("{eventId}", eventId.ToString());
                    return location.ToLowerInvariant();
                }
            }
            public static class DiyMatingEvent
            {
                public const string ResourceName = "ITOperations.Mating.DiyMatingEvent";
                public static string Put(Guid eventId)
                {
                    var location = "v0/event/diymating/{eventId}".Replace("{eventId}", eventId.ToString());
                    return location.ToLowerInvariant();
                }
            }
        }
    }
}